spring:
  datasource:
    url: jdbc:sqlite:telegram.db
    driver-class-name: org.sqlite.JDBC
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://localhost:27017}/vouchers
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: restserver

server:
  port: 8443
  ssl:
    enabled: false
    # need to add your own domain's certificate
    key-store: ${KEYSTORE_PATH}
    key-store-type: PKCS12
    # need to set environment variable
    key-store-password: ${SSL_KEYSTORE_PASSWORD}



telegram:
  # set your own token
  botUrl: "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
  # set your own bot username (get it from BotFather)
  botName: ${BOT_USERNAME}
